In [35]:
import numpy as np

# numpy array

In [2]:
my_list=[1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr1=np.array(my_list)

In [5]:
arr1

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)#it will give the range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,20,2)#we are giving third parameter as stepaside ie it will return even number

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
 np.linspace(0,6,10) #it will return single array of 10 elements between range 0 to 6

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [15]:
#creating identity matrix using numpy
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)#it will give single dimention 5 random number between 0 to 1

array([0.75986459, 0.87860589, 0.14091285, 0.71433253, 0.88461228])

In [17]:
np.random.rand(5,5)#trwo dimetion random number of matrix 585

array([[0.04094948, 0.75251423, 0.60413545, 0.14812417, 0.3403971 ],
       [0.42397204, 0.73380067, 0.95090841, 0.95702936, 0.60871725],
       [0.59425539, 0.16799254, 0.02860152, 0.97286953, 0.93167756],
       [0.55146536, 0.52181362, 0.94504394, 0.40459987, 0.15300795],
       [0.48094368, 0.12145008, 0.61465286, 0.62829567, 0.37907152]])

In [18]:
np.random.randn(2)# it will give 2 element form random normal distribution

array([-0.37555602,  0.60292975])

In [19]:
np.random.randn(4,4)

array([[-1.6786078 ,  0.02149279,  0.97751562, -1.65806401],
       [ 0.86795014,  0.37623033,  0.62554884, -1.19665482],
       [-0.49924048,  0.97072745,  0.34204568, -0.12109692],
       [ 1.00025178,  2.17787918, -0.72034508, -0.73923105]])

In [21]:
np.random.randint(2,400)# it will give random integer between 2 & 400

292

In [22]:
np.random.randint(1,100,11)

array([53, 28, 25, 49,  7, 77, 82, 24, 31, 77, 59])

In [23]:
arr=np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr2=np.random.randint(1,100,10)

In [26]:
arr2

array([28, 29, 49, 46, 42, 45, 55, 69, 14, 93])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr2.max()

93

In [30]:
arr2.min()

14

In [31]:
arr2.argmax()

9

In [32]:
arr2.argmin()

8

In [34]:
arr2.dtype

dtype('int32')

# numpy indexing & selection

In [36]:
arr3=np.arange(0,10)

In [37]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr3[3]

3

In [40]:
arr3[2:4]

array([2, 3])

In [41]:
arr3[:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
arr3[4:]

array([4, 5, 6, 7, 8, 9])

In [43]:
arr3[0:5]=100

In [44]:
arr3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [45]:
slice_of_arr=arr3[3:]

In [47]:
slice_of_arr

array([100, 100,   5,   6,   7,   8,   9])

In [48]:
slice_of_arr[:]=33

In [49]:
slice_of_arr

array([33, 33, 33, 33, 33, 33, 33])

In [50]:
arr3

array([100, 100, 100,  33,  33,  33,  33,  33,  33,  33])

In [51]:
#if we doesnot want any changes in original array we have to copy first

In [52]:
arr_copy=arr3.copy()

In [53]:
arr_copy

array([100, 100, 100,  33,  33,  33,  33,  33,  33,  33])

In [54]:
arr_copy[:]=90

In [55]:
arr_copy

array([90, 90, 90, 90, 90, 90, 90, 90, 90, 90])

In [56]:
arr3

array([100, 100, 100,  33,  33,  33,  33,  33,  33,  33])

# indexing two D array or matrix

In [60]:
arr_2d=np.array([[3,5,4],[4,6,3],[8,4,7]])

In [61]:
arr_2d

array([[3, 5, 4],
       [4, 6, 3],
       [8, 4, 7]])

In [63]:
arr_2d[1][1] #first arguments takes for row & second for column ie it will return the 2nd row 2nd element

6

In [64]:
arr_2d[0]

array([3, 5, 4])

In [67]:
arr_2d[:][1]

array([4, 6, 3])

In [69]:
arr_2d[:]

array([[3, 5, 4],
       [4, 6, 3],
       [8, 4, 7]])

In [70]:
arr_2d[2][0]

8

In [72]:
arr_2d[2,0] #first row 2nd column. this is best practice

8

In [75]:
arr_2d[0:2,1:]

array([[5, 4],
       [6, 3]])

# conditional selection

In [76]:
arrr=np.arange(5,15)

In [77]:
arrr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
bool_arr=arrr>7

In [81]:
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [82]:
arrr[bool_arr]# we are now ckecking all the element present in arrr where bool_arr is true

array([ 8,  9, 10, 11, 12, 13, 14])

In [84]:
arrr[arrr>7]

array([ 8,  9, 10, 11, 12, 13, 14])

In [85]:
arrr[arrr<10]

array([5, 6, 7, 8, 9])

In [88]:
arrr_2d=np.arange(10,60).reshape(5,10)

In [89]:
arrr_2d

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [90]:
arrr_2d[2:,:4]

array([[30, 31, 32, 33],
       [40, 41, 42, 43],
       [50, 51, 52, 53]])