# Numpy operations

#Array with Array
#Array with Scalars
#Universal Array Functions


In [3]:
import numpy as np

In [4]:
arr=np.arange(0,10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr *arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr -5 #SCALAR OPERATIONS ie it will deduct 5 from each elements of the array

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [11]:
arr *3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
arr/arr #it will show warning bcoz of 0/0

<ipython-input-12-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [14]:
#universal array functions

In [15]:
np.sqrt(arr)#it will return square root of the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
arr.max()

9

In [18]:
np.max(arr)

9

In [19]:
np.sin(arr)#we can also use trigonometry function

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [20]:
np.log(arr)

<ipython-input-20-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [21]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])